# Problem 3

In [5]:
import numpy as np
from scipy.linalg import inv
from scipy.linalg import solve
from scipy.linalg import lu


m = 5 ; n = 5

a = np.array([[2 ,-2 ,0 ,0 , 0],
              [-2 ,5,-6 ,0 , 0],
              [0 ,-6 ,16, 12,0],
              [0 ,0 ,12,39, -6],
              [0, 0, 0, -6, 14]])


P, L, U = lu(a)


print("Lower")
print("")
print(L)

print("Upper")
print(" ")
print(U)




Lower

[[ 1.          0.          0.          0.          0.        ]
 [ 0.          1.          0.          0.          0.        ]
 [ 0.         -0.          1.          0.          0.        ]
 [ 0.         -0.          0.          1.          0.        ]
 [-1.         -0.5         0.16666667  0.08333333  1.        ]]
Upper
 
[[ 2.         -2.          0.          0.          0.        ]
 [ 0.         -6.         16.         12.          0.        ]
 [ 0.          0.         12.         39.         -6.        ]
 [ 0.          0.          0.         -6.         14.        ]
 [ 0.          0.          0.          0.         -0.16666667]]


# Problem 4

In [16]:
import numpy as np
from scipy.linalg import inv
from scipy.linalg import solve
from scipy.linalg import lu


m = 5 ; n = 5

a = np.array([[6 ,2 ,0 ,0 , 0],
              [-1 ,7,2 ,0 , 0],
              [0 ,-2 ,8, 2, 0],
              [0 ,0 ,3, 7, -2],
              [0, 0, 0, 3, 5]])

b = np.array([2, -3, 4, -3, 1])
b = b.reshape(5,)
print(b)

P, L, U = lu(a)

[ 2 -3  4 -3  1]


# Problem set 2.1: Problem 15

In [17]:
#hw 1.problem15

import numpy as np 
from numpy import array
from scipy.linalg import qr
from scipy.linalg import hilbert
import numpy as np 
from scipy.linalg import lu
from scipy.linalg import solve

n = 5

A = hilbert(n)

b = np.random.randint(1,n, size = (n,1))

P, L, U = lu(A)


#solve Ax = b
y = solve(L, P.T @ b)
x = solve(U, y)

print("A solution")
print(x)

A solution
[[   1320.00000001]
 [ -26040.00000018]
 [ 116760.00000079]
 [-181440.00000122]
 [  90720.00000061]]


# Problem set 2.1; Problem # 21

In [18]:
#hw1problem21
import numpy as np
from numpy.linalg import norm, inv



a = np.array([[1, 1, 1],
            [2, 2, 1],
            [3, 3, 0]])


infinity_norm = np.absolute(a)



print("Euclidean norm:",np.linalg.norm(a)*np.linalg.norm(np.linalg.pinv(a)))
print("Infinity norm:", np.linalg.norm(infinity_norm)*np.linalg.norm(np.linalg.pinv(infinity_norm)))


#since its a singular matrix it does not have an inverse 

Euclidean norm: 4.866642633922877
Infinity norm: 4.866642633922877


# Problem 23

In [19]:
import numpy
from numpy.random import rand

def gaussElimin(n):
    a = rand(n,n)
    b = numpy.sum(a, axis=1)
    A = numpy.linalg.inv(a)
    x = A @ b
    return x

X = gaussElimin(400)
print(X)

[1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         0.99999999 1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.00000001
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1. 