In [27]:
from math import sqrt
import numpy as np
#problemset 2.1 #7

#Cholesky A = LLT
 
def cholesky(A):
    n = len(A)

    L = [[0.0] * n for i in range(n)]

    for i in range(n):
        for k in range(i+1):
            tmp_sum = sum(L[i][j] * L[k][j] for j in range(k))
            
            if (i == k): 
                L[i][k] = sqrt(A[i][i] - tmp_sum)
            else:
                L[i][k] = (1.0 / L[k][k] * (A[i][k] - tmp_sum))
    return L
 
A  = np.array([[4, -1, 0], 
            [-1, 4, -1],
            [0, -1, 4]])


L = np.matrix(cholesky(A))


LT = L.T
#a = L @ LT - check
print("U:",LT)
print("L:", L)


U: [[ 2.         -0.5         0.        ]
 [ 0.          1.93649167 -0.51639778]
 [ 0.          0.          1.93218357]]
L: [[ 2.          0.          0.        ]
 [-0.5         1.93649167  0.        ]
 [ 0.         -0.51639778  1.93218357]]


In [34]:
#Doolittle decomposition

def luDecomposition(a, n):

    lower = [[0 for x in range(n)]
        for y in range(n)]
    upper = [[0 for x in range(n)]
        for y in range(n)]


    for i in range(n):

        for k in range(i, n):

            sum = 0
            for j in range(i):
                sum += (lower[i][j] * upper[j][k])

            upper[i][k] = mat[i][k] - sum

        for k in range(i, n):
            if (i == k):
                lower[i][i] = 1
            else:

                sum = 0
                for j in range(i):
                    sum += (lower[k][j] * upper[j][i])

                lower[k][i] = int((mat[k][i] - sum) /
                                upper[i][i])

    print("Lower Triangular\t\tUpper Triangular")

    for i in range(n):

        for j in range(n):
            print(lower[i][j], end="\t")
        print("", end="\t")


        for j in range(n):
            print(upper[i][j], end="\t")
        print("")


A  = np.array([[4, -1, 0], 
             [-1, 4, -1],
                [0, -1, 4]])

luDecomposition(A, 3)




Lower Triangular		Upper Triangular
1	0	0		2	-1	-2	
-2	1	0		0	4	-1	
-2	-1	1		0	0	3	
