In [5]:
import numpy as np
from numpy import array
#Problemset 2.1 #7

def LUdecomp(a):
    n = len(a)
    for k in range(0,n-1):
        for i in range(k+1,n):
           if a[i,k] != 0.0:
               lam = a [i,k]/a[k,k]
               a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
               a[i,k] = lam
    return a


A  = array([[4, -1, 0], 
            [-1, 4, -1],
            [0, -1, 4]])

LUdecomp(A)      

array([[ 4, -1,  0],
       [ 0,  3, -1],
       [ 0,  0,  3]])

In [6]:
import numpy as np 
from numpy import array
import math

#Choleski decomposition

def choleski(a):
    n = len(a)
    for k in range(n):
        try:
            a[k,k] = math.sqrt(a[k,k] - np.dot(a[k,0:k],a[k,0:k]))
        except ValueError:
            print('Matrix is not positive definite')
        for i in range(k+1,n):
            a[i,k] = (a[i,k] - np.dot(a[i,0:k],a[k,0:k]))/a[k,k]
    for k in range(1,n): a[0:k,k] = 0.0
    return a


def choleskiSol(L,b):
    n = len(b)
    for k in range(n):
        b[k] = (b[k] - np.dot(L[k,0:k],b[0:k]))/L[k,k]
    for k in range(n-1,-1,-1):
        b[k] = (b[k] - np.dot(L[k+1:n,k],b[k+1:n]))/L[k,k]
    return b

A  = array([[4, -1, 0], 
            [-1, 4, -1],
            [0, -1, 4]])

s= choleski(A)

print(s)


[[2 0 0]
 [0 2 0]
 [0 0 2]]
