In [9]:
from math import sqrt
import numpy as np
#problemset 2.1 #7

#Cholesky A = LLT

def cholesky(A):
    n = len(A)

    L = [[0.0] * n for i in range(n)]

    for i in range(n):
        for k in range(i+1):
            tmp_sum = sum(L[i][j] * L[k][j] for j in range(k))
            
            if (i == k): 
                L[i][k] = sqrt(A[i][i] - tmp_sum)
            else:
                L[i][k] = (1.0 / L[k][k] * (A[i][k] - tmp_sum))
    return L
 
A  = np.array([[4, -1, 0], 
            [-1, 4, -1],
            [0, -1, 4]])


L = np.matrix(cholesky(A))

print(L)

LT = L.T
a = L @ LT 

#print(a)
#print("U:",LT)
#print("L:", L)

print(a - L @LT)

[[ 2.          0.          0.        ]
 [-0.5         1.93649167  0.        ]
 [ 0.         -0.51639778  1.93218357]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
#Doolittle decomposition

def luDecomposition(mat, n):

    lower = [[0 for x in range(n)]
        for y in range(n)]
    upper = [[0 for x in range(n)]
        for y in range(n)]


    for i in range(n):

        for k in range(i, n):

            sum = 0
            for j in range(i):
                sum += (lower[i][j] * upper[j][k])

            upper[i][k] = mat[i][k] - sum

        for k in range(i, n):
            if (i == k):
                lower[i][i] = 1
            else:

                sum = 0
                for j in range(i):
                    sum += (lower[k][j] * upper[j][i])

                lower[k][i] = int((mat[k][i] - sum) /
                                upper[i][i])

    print("Lower Triangular\t\tUpper Triangular")

    for i in range(n):

        for j in range(n):
            print(lower[i][j], end="\t")
        print("", end="\t")


        for j in range(n):
            print(upper[i][j], end="\t")
        print("")


A  = np.array([[4, -1, 0], 
                 [-1, 4, -1],
                [0, -1, 4]])

luDecomposition(A, 3)

Lower Triangular		Upper Triangular
1	0	0		4	-1	0	
0	1	0		0	4	-1	
0	0	1		0	0	4	


In [13]:
#problemset 2.1 #15

import numpy as np 
from numpy import array
from scipy.linalg import qr
from scipy.linalg import hilbert

n = 10

A = hilbert(n)
A

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
        0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667,
        0.14285714, 0.125     , 0.11111111, 0.1       , 0.09090909],
       [0.33333333, 0.25      , 0.2       , 0.16666667, 0.14285714,
        0.125     , 0.11111111, 0.1       , 0.09090909, 0.08333333],
       [0.25      , 0.2       , 0.16666667, 0.14285714, 0.125     ,
        0.11111111, 0.1       , 0.09090909, 0.08333333, 0.07692308],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
        0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ,
        0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667],
       [0.14285714, 0.125     , 0.11111111, 0.1       , 0.09090909,
        0.08333333, 0.07692308, 0.07142857, 0.06666667, 0.0625    ],
       [0.125     , 0.11111111, 0.1      

In [12]:
import numpy as np

def LUdecomp(a):
    n = len(a)
    for k in range(0,n-1):
        for i in range(k+1,n):
           if a[i,k] != 0.0:
               lam = a [i,k]/a[k,k]
               a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
               a[i,k] = lam
    return a

def LUsolve(a,b):
    n = len(a)
    for k in range(1,n):
        b[k] = b[k] - np.dot(a[k,0:k],b[0:k])
    b[n-1] = b[n-1]/a[n-1,n-1]    
    for k in range(n-2,-1,-1):
       b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
    return b

LUdecomp(A)

#solve the system of equation 

array([[1.        , 0.5       , 0.33333333],
       [0.5       , 0.08333333, 0.08333333],
       [0.33333333, 1.        , 0.00555556]])

In [15]:
import numpy as np
from numpy.linalg import solve

#Problemset 2.1 #17 - CORRECT 


def leftMatrix(arr):
    return [1, arr[0], arr[0]**2, arr[0]**3]

def rightMatrix(arr):
    return arr[1]

def solve(A, B):
    A = np.array(A)
    B = np.array(B)
    X2 = np.linalg.solve(A,B)
    return list(X2) 
  

points = np.array([[0, 10],
                   [1, 35], 
                   [3, 31], 
                   [4, 2]])

A = list() 
b = list() 
for i in range(len(points)):
    A.append(leftMatrix(points[i]))
    b.append(rightMatrix(points[i]))  

ans = solve(A, b) 
for i in range(len(ans)):
    print('a', i, '= ', ans[i])

a 0 =  10.0
a 1 =  34.0
a 2 =  -9.0
a 3 =  0.0


In [16]:
import numpy as np
from numpy.linalg import norm, inv

#Problemset 2.1 #21


a = np.array([[1, 1, 1],
            [2, 2, 1],
            [3, 3, 0]])


infinity_norm = np.absolute(a)



print("Euclidean norm:",np.linalg.norm(a)*np.linalg.norm(np.linalg.pinv(a)))
print("Infinity norm:", np.linalg.norm(infinity_norm)*np.linalg.norm(np.linalg.pinv(infinity_norm)))


#since its a singular matrix it does not have an inverse 
#
#euclidean norm = close to 12.437
#infinity condition norm = close to 15

Euclidean norm: 4.866642633922877
Infinity norm: 4.866642633922877


In [17]:
import numpy
from numpy.random import rand

#Problemset 2.1 #23



def gaussElimin(n):
    a = rand(n,n)
    b = numpy.sum(a, axis=1)
    A = numpy.linalg.inv(a)
    x = A @ b
    return x

X = gaussElimin(1000)
print(X)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

In [18]:
import numpy as np
#Problem set 2.2 #3

a = np.array([[2,-2 , 0, 0, 0],
            [-2, 5, -6, 0, 0],
            [0, -6, 16, 12, 0],
            [0, 0, 12, 39, -6],
            [0, 0, 0, -6, 14]])


def doolittle_decomp(a):
    s = len(a)
    L = [[0 for i in range(s)] for j in range(s)]
    D = [[0 for i in range(s)] for j in range(s)]
    
    for i in range(s):
        for j in range(i, s):
            total = 0
            for k in range(i):
                total += (L[i][k] * D[k][j])
            
            D[i][j] = a[i][j] - total
    
    for j in range(i, s):
        if(i == j):
            L[i][i] = 1
        else:
            total = 0
            for k in range(i):
                total += (L[j][k] * D[k][i])
            
            L[i][j] = int((a[j][i] - total)/D[i][i])
                
    return L, D

L, D = doolittle_decomp(a)
print("L: ",np.matrix(L))
print(" ")
print("D: ",np.matrix(D))
#diagonal matrix - 


L:  [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 1]]
 
D:  [[ 2 -2  0  0  0]
 [ 0  5 -6  0  0]
 [ 0  0 16 12  0]
 [ 0  0  0 39 -6]
 [ 0  0  0  0 14]]


In [17]:
import numpy as np
from scipy.linalg import diagsvd
from scipy.linalg import pinv
from scipy.linalg import svd

m = 5;n = 10 

A = np.array([[7, -4, 1, 0, 0, 0, 0, 0, 0, 0],
              [-4, 6, -4, 1, 0, 0, 0, 0, 0, 0],
              [1, 0, -4, 0, 6, 0, -4, 0, 0, 1],
              [0, 0, 0, 0, 0, 0, 1, -4, 6, -4],
              [0, 0, 0, 0, 0, 0, 0, 1, -4, 7]])

U, sigma, VT = svd(A)


Sigma = diagsvd(sigma, m, n)

b = np.ones(5, dtype= int)


Sigma = diagsvd(sigma, m, n)

PseudoA = (VT).T @ pinv(Sigma) @ U.T 

x = PseudoA @  b
print(x)

#solve again

[ 0.27533067  0.16965588 -0.24869113  0.08862284 -0.0229199   0.
  0.10095023 -0.25443458  0.16103533  0.27122513]
