In [5]:
import numpy as np 
#from numpy import array
from scipy.linalg import solve
from scipy.linalg import lu

#PROBLEM 1

m = 5 ; n = 3


A = np.random.randint(-2,5 , size=(m, n) )

b = np.random.randint(-2,3, size=(m, 1))


ATA = A.T @ A


AAT = A @ A.T

ATb = A.T @ b



P, L, U = lu(ATA)

P1, L1, U1 = lu(AAT)


#solve ATAx = ATb
y = solve(L, P.T @ ATb)
x = solve(U, y)

#solve AATx = b, AAT  - problem is singular
y1 = solve(L1, P1.T @ b)
x1 = solve(U1, y1)

print("ATA solution")
print(x)
print(" ")
print("AAT solution")
print(x1)

ATA solution
[[ 0.32050385]
 [-0.15675297]
 [ 0.25297411]]
 
AAT solution
[[ 9.50045064e+14]
 [ 3.97817967e+14]
 [-3.53318114e+14]
 [ 1.93011413e+14]
 [-4.87889960e+14]]


<ipython-input-5-23fb6123ded7>:36: LinAlgWarning: Ill-conditioned matrix (rcond=5.82835e-18): result may not be accurate.
  x1 = solve(U1, y1)


In [13]:
#PROBLEM 2
import numpy as np 
from scipy.linalg import ldl
from scipy.linalg import solve
from scipy.linalg import diagsvd



#A = np.random.randint(-2,5, size = (5,3))
#b = np.random.randint(-2,3, size = (5,1))

AAT = A @ A.T

ATA = A.T @ A

ATb = A.T @ b




L, D, p = ldl(ATA)

L1, D1, p1 = ldl(AAT)

 
z = solve(L , ATb)
y = solve(D, z)
x = solve(L.T, y)

z1 = solve(L1, b)
y1 = solve(D1, z1)
x1 = solve(L1.T, y1)
print("ATA solution")
print(x)
print("AAT solution")
print(x1)


ATA solution
[[-0.71164309]
 [ 0.56692057]
 [-0.37431991]]
AAT solution
[[ 2.01437425e+15]
 [-2.71147830e+15]
 [ 7.09927035e+14]
 [-6.01747677e+15]
 [ 1.34291616e+15]]


<ipython-input-13-fa0341147d39>:31: LinAlgWarning: Ill-conditioned matrix (rcond=1.49453e-17): result may not be accurate.
  y1 = solve(D1, z1)


In [24]:
#PROBLEM 3

import numpy as np 
from scipy.linalg import solve
from scipy.linalg import cholesky
from scipy.linalg import norm, solve_triangular



A = np.random.randint(-2,5, size = (5,3))
b = np.random.randint(-2,3, size = (5,1))

AAT = A @ A.T

ATA = A.T @ A

ATb = A.T @ b

R = cholesky(ATA)
R1 = cholesky(AAT) 


w = solve(R.T, ATb)
x = solve(R, w)

w1 = solve(R1.T, b)
x1 = solve(R1,w1)

print("ATA solution")
print(x)
print(" ")
print("AAT solution") #problem just needs a matrix that works
print(x1)

ATA solution
[[-0.02508961]
 [-0.23835125]
 [ 0.27240143]]
 
AAT solution
[[ 7.30427565e+15]
 [-2.05476733e+15]
 [ 2.95548726e+15]
 [ 2.46290605e+15]
 [ 1.06960491e+15]]


In [5]:
# PROBLEM #4
from numpy import array
import numpy as np
from numpy.linalg import eig

m = 5 ; n = 3

#A = np.random.randint(-2,5 , size=(m, n) )

 

print("Original Matrix")
print(A)
print(" ------------- ")

ATA = A.T @ A

Eig_Values, Eig_Vectors = eig(ATA)
#
print("EigenValues of ATA")
print(Eig_Values)
print(" ------------- ")
#
print("EigenVectors of ATA")
print(Eig_Vectors)
print(" ------------- ")
 
AAT = A @ A.T

Eig_Values, Eig_Vectors = eig(AAT)
#
print("EigenValues of AAT")
print(Eig_Values)
print(" ------------- ")
#
print("EigenVectors of AAT")
print(Eig_Vectors)
print(" ------------- ")

Original Matrix
[[ 0  2 -1]
 [ 1  3  4]
 [-1  3  4]
 [ 3  3  2]
 [ 1 -2  0]]
 ------------- 
EigenValues of ATA
[65.59019059 10.69928699  7.71052242]
 ------------- 
EigenVectors of ATA
[[ 0.16885016  0.93972129  0.29734413]
 [ 0.68623823  0.10446465 -0.71983625]
 [ 0.7075074  -0.32559337  0.6272338 ]]
 ------------- 
EigenValues of AAT
[6.55901906e+01 7.71052242e+00 1.06992870e+01 5.34796865e-16
 3.28091385e-15]
 ------------- 
EigenVectors of AAT
[[ 0.08210734  0.74435291  0.16341379  0.63258722 -0.40789601]
 [ 0.62448866 -0.23292084 -0.01505919  0.06661669 -0.67906638]
 [ 0.58279096 -0.01875635 -0.58964069  0.19092941  0.36332581]
 [ 0.49146679  0.00468484  0.75860254 -0.19879859  0.42753312]
 [-0.14861828 -0.62555007  0.22341708  0.72070848 -0.24020717]]
 ------------- 


In [6]:
import numpy as np
from numpy.linalg import qr 
A1 = np.random.randint(-2,5 , size=(m, n))

A1 = A1.T @ A1



print("A1 = ")
print(A1)

MaxIter = 60; p = [1, 10, 20, MaxIter]
A = A1
for i in range(MaxIter):
    Q, R = qr(A)
    A = R @ Q

    if i+1 in p:
        print(f'Iteration {i+1}:')
        print(R)
        
print("A = ")
print(A)

A1 = 
[[10  5 -4]
 [ 5 26  9]
 [-4  9 11]]
Iteration 1:
[[-11.87434209 -12.12698766   3.28439249]
 [  0.         -25.1979398  -14.00232678]
 [  0.           0.           3.33880379]]
Iteration 10:
[[-3.06315614e+01 -1.15859479e-01 -1.05186375e-09]
 [ 0.00000000e+00 -1.40464642e+01  1.12488610e-06]
 [ 0.00000000e+00  0.00000000e+00  2.32182422e+00]]
Iteration 20:
[[-3.06318388e+01 -4.76253006e-05  3.09766661e-15]
 [ 0.00000000e+00 -1.40463369e+01  1.49776978e-14]
 [ 0.00000000e+00  0.00000000e+00  2.32182422e+00]]
Iteration 60:
[[-3.06318388e+01  4.57554532e-15  3.09767125e-15]
 [ 0.00000000e+00 -1.40463369e+01 -2.15284145e-15]
 [ 0.00000000e+00  0.00000000e+00  2.32182422e+00]]
A = 
[[ 3.06318388e+01 -4.57647754e-15  3.09767125e-15]
 [ 4.27470254e-19  1.40463369e+01 -2.15284145e-15]
 [-2.40768695e-66  1.30692501e-46  2.32182422e+00]]


In [7]:
import numpy as np
from numpy.linalg import qr 
#
A1 = np.random.randint(-2,5 , size=(m, n))

A1 = A1 @ A1.T



print("A1 = ")
print(A1)

MaxIter = 60; p = [1, 10, 20, MaxIter]
A = A1
for i in range(MaxIter):
    Q, R = qr(A)
    A = R @ Q

    if i+1 in p:
        print(f'Iteration {i+1}:')
        print(R)

print("A = ")
print(A)

A1 = 
[[20 16 14  4 -8]
 [16 13 11  1 -7]
 [14 11 11  4 -5]
 [ 4  1  4 26  5]
 [-8 -7 -5  5  5]]
Iteration 1:
[[-3.05286750e+01 -2.43050181e+01 -2.18155553e+01 -7.07531525e+00
   1.18577043e+01]
 [ 0.00000000e+00 -2.29479725e+00  1.40642831e+00  2.61311387e+01
   6.88439175e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.05047822e+00  1.05047822e+00
   3.21725526e-15]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  9.99944449e-15
   3.06763344e-15]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  -2.55541553e-15]]
Iteration 10:
[[-4.68359147e+01  2.08452958e-02 -2.18998574e-14  2.27049459e-15
   6.32997944e-15]
 [ 0.00000000e+00 -2.70972033e+01 -5.70878828e-12 -8.86353187e-15
   1.06036092e-15]
 [ 0.00000000e+00  0.00000000e+00 -1.06687905e+00  2.08790709e-16
   2.64628686e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  6.08291062e-16
  -5.37573851e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  -2.28321406e-15]]
Iteration 20:
[[-4.68359

In [31]:
# PROBLEM 5

import numpy as np 
from scipy.linalg import qr
from scipy.linalg import solve



m = 5 ; n = 3

choice = 0 


A = np.random.randint(-2,5 , size=(m, n))

b = np.random.randint(-2,3, size=(m, 1))

ATA = A.T @ A
AAT = A @ A.T
ATb = A.T @ b


Q1, R1 = qr(A, mode='economic')
Q, R = qr(AAT, mode='economic')
QQ, RR = qr(ATA, mode='economic')

print("Ax = b")
x = solve(R1, Q1.T @ b)  
  
print(" ")
print("A solution")
print(x)
print(" ")


   
print("ATA = Atb")
print("ATA solution")
f = solve(RR, QQ.T @ A.T @ b)
print(f) 
print(" ")

print("AA.T solution")
d = solve(R,Q.T @ b) 
print(d)

Ax = b
 
A solution
[[ 0.45788474]
 [ 0.29385687]
 [-0.27696855]]
 
ATA = Atb
ATA solution
[[ 0.45788474]
 [ 0.29385687]
 [-0.27696855]]
 
AA.T solution
[[ 2.45933804e+15]
 [-3.65391332e+15]
 [-2.25666060e+15]
 [ 7.22403479e+15]
 [ 4.02417446e+15]]


<ipython-input-31-7410184f9125>:44: LinAlgWarning: Ill-conditioned matrix (rcond=2.07193e-18): result may not be accurate.
  d = solve(R,Q.T @ b)
