In [23]:
import numpy as np 
#from numpy import array
from scipy.linalg import solve
from scipy.linalg import lu

#PROBLEM 1

m = 5 ; n = 3


A = np.random.randint(-2,5 , size=(m, n) )

b = np.random.randint(-2,3, size=(m, 1))


ATA = A.T @ A


AAT = A @ A.T

ATb = A.T @ b



P, L, U = lu(ATA)

P1, L1, U1 = lu(AAT)


#solve ATAx = ATb
y = solve(L, P.T @ ATb)
x = solve(U, y)

#solve AATx = b, AAT  - problem is singular
y1 = solve(L1, P1.T @ b)
x1 = solve(U1, y1)

print("ATA solution")
print(x)
print(" ")
print("AAT solution")
print(x1)

ATA solution
[[0.20503145]
 [0.12704403]
 [0.09685535]]
 
AAT solution
[[ 6.95262340e+15]
 [ 3.29791656e+15]
 [-7.75492283e+15]
 [-8.91018294e+14]
 [ 2.68071406e+14]]


<ipython-input-23-23fb6123ded7>:36: LinAlgWarning: Ill-conditioned matrix (rcond=2.23156e-18): result may not be accurate.
  x1 = solve(U1, y1)


In [25]:
#PROBLEM 2
import numpy as np 
from scipy.linalg import ldl
from scipy.linalg import solve
from scipy.linalg import diagsvd



A = np.random.randint(-2,5, size = (5,3))
b = np.random.randint(-2,3, size = (5,1))

AAT = A @ A.T

ATA = A.T @ A

ATb = A.T @ b




L, D, p = ldl(ATA)

L1, D1, p1 = ldl(AAT)

 
z = solve(L , ATb)
y = solve(D, z)
x = solve(L.T, y)

z1 = solve(L1, b)
y1 = solve(D1, z1)
x1 = solve(L.T, y)
print("ATA solution")
print(x)
print("AAT solution")
print(x1)


ATA solution
[[ 0.47947328]
 [ 0.13632843]
 [-0.77769171]]
AAT solution
[[ 0.47947328]
 [ 0.13632843]
 [-0.77769171]]


<ipython-input-25-fd1503228994>:31: LinAlgWarning: Ill-conditioned matrix (rcond=4.44763e-17): result may not be accurate.
  y1 = solve(D1, z1)


In [26]:
#PROBLEM 3

import numpy as np 
from scipy.linalg import solve
from scipy.linalg import cholesky
from scipy.linalg import norm, solve_triangular



A = np.random.randint(-2,5, size = (5,3))
b = np.random.randint(-2,3, size = (5,1))

AAT = A @ A.T

ATA = A.T @ A

ATb = A.T @ b

R = cholesky(ATA)

#R1 = cholesky(AAT) #LinAlgError: 1-th leading minor of the array is not positive definite


w = solve(R.T, ATb)
x = solve(R, w)

#w1 = solve(R1.T, b)
#x1 = solve(R1,w1)

print("ATA solution")
print(x)
print(" ")
print("AAT solution")
#print(x1)
print("No solution")

ATA solution
[[-0.26006711]
 [ 0.5352349 ]
 [ 0.48657718]]
 
AAT solution
No solution


In [28]:
# PROBLEM #4
from numpy import array
import numpy as np
from numpy.linalg import eig

m = 5 ; n = 3

A = np.random.randint(-2,5 , size=(m, n) )

 

print("Original Matrix")
print(A)
print(" ------------- ")

ATA = A.T @ A

Eig_Values, Eig_Vectors = eig(ATA)
#
print("EigenValues of ATA")
print(Eig_Values)
print(" ------------- ")
#
print("EigenVectors of ATA")
print(Eig_Vectors)
print(" ------------- ")
 
AAT = A @ A.T

Eig_Values, Eig_Vectors = eig(AAT)
#
print("EigenValues of AAT")
print(Eig_Values)
print(" ------------- ")
#
print("EigenVectors of AAT")
print(Eig_Vectors)
print(" ------------- ")



Original Matrix
[[ 2  2  4]
 [ 1  4  4]
 [ 0  2  0]
 [-1  2  3]
 [ 0 -1 -2]]
 ------------- 
EigenValues of ATA
[71.75448645  4.92880488  3.31670867]
 ------------- 
EigenVectors of ATA
[[-0.16189873 -0.74279084 -0.6496542 ]
 [-0.60576722  0.59450853 -0.52877753]
 [-0.77899607 -0.30793081  0.54620852]]
 ------------- 
EigenValues of AAT
[ 7.17544865e+01  4.92880488e+00  3.31670867e+00 -2.52129426e-15
 -2.91499278e-16]
 ------------- 
EigenVectors of AAT
[[ 0.54909986  0.68838967 -0.09446022  0.43354507 -0.00351364]
 [ 0.67301206 -0.18175833 -0.31843596 -0.6419467  -0.24699874]
 [ 0.14302476 -0.53557127 -0.58069666  0.58566084  0.31050525]
 [ 0.39979968 -0.45404238  0.67578298  0.22514343 -0.25402602]
 [-0.25543737 -0.00961811 -0.30949081 -0.07908811 -0.8820638 ]]
 ------------- 


In [29]:
import numpy as np
from numpy.linalg import qr 
#
A1 = np.random.randint(-2,5 , size=(m, n))

A1 = A1.T @ A1



print("A1 = ")
print(A1)

MaxIter = 60; p = [1, 10, 20, MaxIter]
A = A1
for i in range(MaxIter):
    Q, R = qr(A)
    A = R @ Q

    if i+1 in p:
        print(f'Iteration {i+1}:')
        print(R)

print("A = ")
print(A)

A1 = 
[[ 4 -3 -2]
 [-3 16  9]
 [-2  9 22]]
Iteration 1:
[[ -5.38516481  14.48423638  14.66993172]
 [  0.         -11.67077104 -11.61167852]
 [  0.           0.          14.79736549]]
Iteration 10:
[[-2.89454044e+01  2.09635776e-03 -6.56423260e-06]
 [ 0.00000000e+00 -9.76393667e+00  2.98020900e-02]
 [ 0.00000000e+00  0.00000000e+00  3.29062485e+00]]
Iteration 20:
[[-2.89454045e+01  3.99892863e-08 -3.06766214e-15]
 [ 0.00000000e+00 -9.76398795e+00  5.63297920e-07]
 [ 0.00000000e+00  0.00000000e+00  3.29060756e+00]]
Iteration 60:
[[-2.89454045e+01  2.22263189e-15 -7.00918371e-16]
 [ 0.00000000e+00 -9.76398795e+00  1.40372186e-15]
 [ 0.00000000e+00  0.00000000e+00  3.29060756e+00]]
A = 
[[ 2.89454045e+01 -2.22263189e-15 -7.00918371e-16]
 [-1.33554641e-27  9.76398795e+00  1.40372186e-15]
 [-3.33187677e-54  1.81219556e-26  3.29060756e+00]]


In [30]:
import numpy as np
from numpy.linalg import qr 
#
A1 = np.random.randint(-2,5 , size=(m, n))

A1 = A1 @ A1.T



print("A1 = ")
print(A1)

MaxIter = 60; p = [1, 10, 20, MaxIter]
A = A1
for i in range(MaxIter):
    Q, R = qr(A)
    A = R @ Q

    if i+1 in p:
        print(f'Iteration {i+1}:')
        print(R)

print("A = ")
print(A)

A1 = 
[[29  3  8 30 -1]
 [ 3  6  4  3 -3]
 [ 8  4  4  8 -2]
 [30  3  8 33  0]
 [-1 -3 -2  0  2]]
Iteration 1:
[[-4.26028168e+01 -5.39870406e+00 -1.21588204e+01 -4.53725867e+01
   1.31446708e+00]
 [ 0.00000000e+00 -7.06073612e+00 -4.01631307e+00  8.43137025e-01
   3.95193657e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.79763034e-01  1.61786730e+00
   8.08933652e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -5.60525207e-15
  -2.53654698e-15]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  -2.99064057e-16]]
Iteration 10:
[[-6.36735904e+01 -1.27376565e-07  2.22981668e-14  1.34281862e-16
  -5.68443104e-16]
 [ 0.00000000e+00 -9.05913300e+00 -1.01521546e-07 -4.90766184e-16
   1.07101083e-15]
 [ 0.00000000e+00  0.00000000e+00 -1.26727656e+00  8.21985244e-16
  -6.65598844e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -5.21729445e-16
   2.08167011e-17]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  -2.37675999e-16]]
Iteration 20:
[[-6.36735

In [31]:
# PROBLEM 5

import numpy as np 
from scipy.linalg import qr
from scipy.linalg import solve
#

m = 5 ; n = 3

choice = 0 


A = np.random.randint(-2,5 , size=(m, n))
b = np.random.randint(-2,3, size=(m, 1))

ATA = A.T @ A
AAT = A @ A.T
ATb = A.T @ b

if choice == 0: 
     Q, R = qr(A, mode='economic')
else:
     Q, R = qr(A, mode='full')

#
if choice == 0: 
  x = solve(R, Q.T @ b)  
  
  print(" ")
  print("A solution")
  print(x)
  print(" ")
    

print("ATA solution")
x = solve(R.T @ R, A.T @ b)
print(x)
print(" ")

print("AA.T solution")
#d = solve(R @ R.T, b) 
print("No solution") #ValueError: Input b has to have same number of rows as input a

 
A solution
[[-0.51162791]
 [ 0.44518272]
 [ 0.80730897]]
 
ATA solution
[[-0.51162791]
 [ 0.44518272]
 [ 0.80730897]]
 
AA.T solution
No solution
