In [1]:
import numpy as np
from numpy.linalg import eig

A = np.random.randint(0, 5,size = (4,3))
b = np.random.randint(-1,3, size = (4,1))

ATA = A.T @ A 
AAT = A @ A.T

eig_values, eig_vectors = eig(ATA)
eig_values1, eig_vectors1 = eig(AAT)

print("ATA eig_values")
print(eig_values)
print(" ")
print("ATA eig_vectors")
print(eig_vectors)
print(" ")
print("AAT eig_values")
print(eig_values1)
print(" ")
print("AAT eig_vectors")
print(eig_vectors1)

ATA eig_values
[54.03770902  3.          0.96229098]
 
ATA eig_vectors
[[-5.66263346e-01 -7.07106781e-01 -4.23492412e-01]
 [-5.66263346e-01  7.07106781e-01 -4.23492412e-01]
 [-5.98908712e-01 -1.21297886e-15  8.00817304e-01]]
 
AAT eig_values
[5.40377090e+01 2.39599217e-16 9.62290981e-01 3.00000000e+00]
 
AAT eig_vectors
[[-1.54063579e-01 -4.80384461e-01 -8.63420629e-01 -3.26231024e-16]
 [-4.71072579e-01  3.20256308e-01 -9.41268063e-02 -8.16496581e-01]
 [-8.65113369e-01 -1.60128154e-01  2.43456702e-01  4.08248290e-01]
 [-7.70317895e-02  8.00640769e-01 -4.31710315e-01  4.08248290e-01]]
