In [3]:
import numpy as np
from numpy import array
from scipy.linalg import solve
from scipy.linalg import qr



#PROBLEM 1

A = np.random.randint(0, 5, size=(4, 3))
b = np.random.randint(-1,3, size=(4, 1))
c = np.random.randint(-1,3 ,size=(3, 1))

AT = A.T 

Q, R = qr(A,mode = "economic")

print("Ax = b solution")
x = solve(R, Q.T @ b)
print(x)
print(" ")


QQ, RR = qr(AT, mode = "economic")

#y = solve(RR, QQ.T @ c)
#print(y)
#print("ATy = c")
#print(y)

Ax = b solution
[[ 1.5]
 [ 5. ]
 [-7. ]]
 


In [8]:
import numpy as np
from scipy.linalg import diagsvd
from scipy.linalg import pinv
#from scipy.linalg import inv
from scipy.linalg import svd

#PROBLEM 2

m = 4 ; n = 3

A = np.random.randint(0, 5, size=(m, n))
b = np.random.randint(-1, 3, size=(m, 1) )
c = np.random.randint(-1, 3, size=(n, 1) )

AT = A.T



U, sigma, VT = svd(A)
Sigma = diagsvd(sigma, m, n)

PseudoA = (VT).T @ pinv(Sigma) @ U.T 

#####################################

U1, sigma1, VT1 = svd(AT)
Sigma1 = diagsvd(sigma1,n, m) 

PseudoA1 = VT1.T @ pinv(Sigma1) @ U1.T 


x = PseudoA @ b
print("Ax = b solution")
print(x)
print(" ")
print("ATy = c solution")
x1 = PseudoA1 @ c
print(x1)

Ax = b solution
[[ 2.22044605e-15]
 [ 6.66666667e-01]
 [-2.22222222e-01]]
 
ATy = c solution
[[ 0.66666667]
 [-0.55555556]
 [ 0.44444444]
 [-0.11111111]]


In [10]:
import numpy as np 
from scipy.linalg import solve
from scipy.linalg import cholesky
from scipy.linalg import norm, solve_triangular

#PROBLEM 3

A = np.random.randint(0,5, size = (4,3))
b = np.random.randint(-1,3, size = (4,1))


ATA = A.T @ A

ATb = A.T @ b


R = cholesky(ATA)


w = solve(R.T, ATb)
x = solve(R, w)


print("ATA solution")
print(x)

ATA solution
[[ 0.3380486 ]
 [-0.49183896]
 [ 0.07072905]]


In [11]:
# PROBLEM 4

import numpy as np 
#from numpy import array
from scipy.linalg import qr
#from scipy.linalg import inv
#from scipy.linalg import pinv
from scipy.linalg import solve


m = 4 ; n = 3


A = np.random.randint(0,5 , size=(m, n) )

ATA = A.T @ A

b = np.random.randint(-1,3, size=(m, 1))



Q, R = qr(ATA, mode='economic')

        
print("ATA solution")
x1 = solve(R, Q.T @ A.T @ b)
print(x1)
print(" ")

ATA solution
[[-2.]
 [ 1.]
 [ 1.]]
 


In [12]:
#PROBLEM 5

import numpy as np 
from scipy.linalg import ldl
from scipy.linalg import solve
from scipy.linalg import diagsvd
from scipy.linalg import svd, pinv

m = 4 ; n = 3



A = np.random.randint(0,5, size = (4,3))
b = np.random.randint(-1,3, size = (4,1))
c = np.random.randint(-1, 3, size =(3,1))

ATA = A.T @ A

ATb = A.T @ b

U1, sigma1, VT1 = svd(ATA)


Sigma1 = diagsvd(sigma1,3,3) 

PseudoA1 = VT1.T @ pinv(Sigma1) @ U1.T 
x = PseudoA1 @ A.T @ b
print("ATA solution")
print(x)

ATA solution
[[-0.46938776]
 [ 1.0952381 ]
 [-0.26530612]]


In [13]:
#PROBLEM 6

import numpy as np
from numpy.linalg import eig

A = np.random.randint(0, 5,size = (4,3))
b = np.random.randint(-1,3, size = (4,1))

ATA = A.T @ A 
AAT = A @ A.T

eig_values, eig_vectors = eig(ATA)
eig_values1, eig_vectors1 = eig(AAT)

print("ATA eig_values")
print(eig_values)
print(" ")
print("ATA eig_vectors")
print(eig_vectors)
print(" ")
print("AAT eig_values")
print(eig_values1)
print(" ")
print("AAT eig_vectors")
print(eig_vectors1)

ATA eig_values
[48.92250568 17.30447452  1.77301979]
 
ATA eig_vectors
[[-0.63832757 -0.71838168  0.27652429]
 [-0.57464942  0.2057016  -0.79212682]
 [-0.51216791  0.66454091  0.54412262]]
 
AAT eig_values
[ 4.89225057e+01  1.73044745e+01 -3.71381633e-16  1.77301979e+00]
 
AAT eig_vectors
[[ 0.53937238  0.78734974 -0.25811287  0.15011851]
 [ 0.50239285 -0.14913024  0.10324515 -0.84540052]
 [ 0.420064   -0.08673822  0.82596117  0.36580167]
 [ 0.52936292 -0.59187586 -0.49041445  0.35909822]]


In [25]:
#PROBLEM 7

import numpy as np
from scipy.linalg import diagsvd
from scipy.linalg import pinv
#from scipy.linalg import inv
from scipy.linalg import svd

m = 4 ; n = 3

A = np.random.randint(0, 5, size=(m, n) )
b = np.random.randint(-1, 3, size=(m, 1))

print(A)


U, sigma, VT = svd(A)
Sigma = diagsvd(sigma, m, n)
PseudoA = (VT).T @ pinv(Sigma) @ U.T 
print(PseudoA)
print(" ---Verify  A * A^+ * A = A    ----" )
print(  A @ PseudoA @ A )
print(" ---Verify  A^+ * A * A^+ = A^+    ----" )
print(  PseudoA @ A @ PseudoA )

[[4 3 4]
 [3 4 3]
 [2 2 2]
 [4 2 4]]
[[ 0.06349206 -0.11904762 -0.01587302  0.15873016]
 [-0.04761905  0.38095238  0.0952381  -0.28571429]
 [ 0.06349206 -0.11904762 -0.01587302  0.15873016]]
 ---Verify  A * A^+ * A = A    ----
[[4. 3. 4.]
 [3. 4. 3.]
 [2. 2. 2.]
 [4. 2. 4.]]
 ---Verify  A^+ * A * A^+ = A^+    ----
[[ 0.06349206 -0.11904762 -0.01587302  0.15873016]
 [-0.04761905  0.38095238  0.0952381  -0.28571429]
 [ 0.06349206 -0.11904762 -0.01587302  0.15873016]]
