In [8]:
import numpy as np
from numpy import array
from scipy.linalg import solve

#PROBLEM 1

A = np.random.randint(0, 5, size=(4, 3))
b = np.random.randint(-1,3, size=(4, 1))
c = np.random.randint(-1,3 ,size=(3, 1))

AT = A.T

Q, R = qr(A)

y = solve(Q, b)
print("Ax = b solution")
x = solve(R.T @ R, R.T @ y)
print(x)

Ax = b solution
[[-3.56603774]
 [ 0.37735849]
 [ 0.60377358]]


In [10]:
import numpy as np
from scipy.linalg import diagsvd
from scipy.linalg import pinv
#from scipy.linalg import inv
from scipy.linalg import svd

#PROBLEM 2

m = 4 ; n = 3

A = np.random.randint(0, 5, size=(m, n))
b = np.random.randint(-1, 3, size=(m, 1) )
c = np.random.randint(-1, 3, size=(n, 1) )

AT = A.T




U, sigma, VT = svd(A)
Sigma = diagsvd(sigma, m, n)

PseudoA = (VT).T @ pinv(Sigma) @ U.T 


U1, sigma1, VT1 = svd(AT)
Sigma1 = diagsvd(sigma1,m, n)

#PseudoA1 = VT1.T @ pinv(Sigma1) @ U1.T 


x = PseudoA @  b
print("Ax = b solution")
print(x)

Ax = b solution
[[-1.03409091]
 [ 0.97727273]
 [ 0.63636364]]


In [12]:
import numpy as np 
from scipy.linalg import solve
from scipy.linalg import cholesky
from scipy.linalg import norm, solve_triangular

#PROBLEM 3

A = np.random.randint(0,5, size = (4,3))
b = np.random.randint(-1,3, size = (4,1))


ATA = A.T @ A

ATb = A.T @ b

R = cholesky(ATA)



w = solve(R.T, ATb)
x = solve(R, w)


print("ATA solution")
print(x)

ATA solution
[[-0.65957447]
 [-0.4787234 ]
 [ 0.95744681]]


In [13]:
# PROBLEM 4

import numpy as np 
#from numpy import array
from scipy.linalg import qr
#from scipy.linalg import inv
#from scipy.linalg import pinv
from scipy.linalg import solve
#

m = 4 ; n = 3

choice = 0 


A = np.random.randint(0,5 , size=(m, n) )


b = np.random.randint(-1,3, size=(m, 1))


if choice == 0: 
     Q, R = qr(A, mode='economic')
else:
     Q, R = qr(A, mode='full')


print("ATA solution")
x1 = solve(R.T @ R, A.T @ b)
print(x1)
print(" ")

ATA solution
[[ 0.86425339]
 [-1.88687783]
 [ 0.19004525]]
 


In [14]:
#PROBLEM 5

import numpy as np 
from scipy.linalg import ldl
from scipy.linalg import solve
from scipy.linalg import diagsvd
from scipy.linalg import svd, pinv

m = 4 ; n = 3



A = np.random.randint(0,5, size = (4,3))
b = np.random.randint(-1,3, size = (4,1))
c = np.random.randint(-1, 3, size =(3,1))

ATA = A.T @ A

ATb = A.T @ b

U, sigma, VT = svd(ATA)



V = VT.T


Sigma = diagsvd(sigma, n, n)

z = U.T @ ATb
z



y = pinv(Sigma) @ z

x = V @ y

print("ATA solution")
print(x)



ATA solution
[[ 0.41860465]
 [-0.02325581]
 [ 0.09302326]]


In [16]:
#PROBLEM 6

import numpy as np
from numpy.linalg import eig

A = np.random.randint(0, 5,size = (4,3))
b = np.random.randint(-1,3, size = (4,1))

ATA = A.T @ A 
AAT = A @ A.T

eig_values, eig_vectors = eig(ATA)
eig_values1, eig_vectors1 = eig(AAT)

print("ATA eig_values")
print(eig_values)
print(" ")
print("ATA eig_vectors")
print(eig_vectors)
print(" ")
print("AAT eig_values")
print(eig_values1)
print(" ")
print("AAT eig_vectors")
print(eig_vectors1)

ATA eig_values
[68.89799679  0.49819917  7.60380404]
 
ATA eig_vectors
[[ 0.36929457  0.91607776 -0.15627881]
 [ 0.56092879 -0.35380733 -0.74845124]
 [ 0.74093212 -0.18873769  0.64451352]]
 
AAT eig_values
[6.88979968e+01 7.60380404e+00 1.76666699e-15 4.98199166e-01]
 
AAT eig_vectors
[[ 5.81192198e-01  2.78728582e-01  5.57086015e-01  5.23623127e-01]
 [ 5.36701459e-01  3.35402684e-01  1.02177090e-14 -7.74245816e-01]
 [ 2.47224320e-01 -8.70945743e-01  3.71390676e-01 -2.05918952e-01]
 [ 5.59506308e-01 -2.26426435e-01 -7.42781353e-01  2.89757869e-01]]


In [17]:
#PROBLEM 7

import numpy as np
from scipy.linalg import diagsvd
from scipy.linalg import pinv
#from scipy.linalg import inv
from scipy.linalg import svd

m = 4 ; n = 3

A = np.random.randint(0, 5, size=(m, n) )
b = np.random.randint(-1, 3, size=(m, 1))

U, sigma, VT = svd(A)
Sigma = diagsvd(sigma, m, n)
PseudoA = (VT).T @ pinv(Sigma) @ U.T 
print(" ---Verify  A * A^+ * A = A    ----" )
print(  A @ PseudoA @ A )
print(" ---Verify  A^+ * A * A^+ = A^+    ----" )
print(  PseudoA @ A @ PseudoA )

 ---Verify  A * A^+ * A = A    ----
[[2.00000000e+00 4.00000000e+00 7.99360578e-15]
 [1.00000000e+00 1.00000000e+00 2.00000000e+00]
 [1.00000000e+00 1.00000000e+00 3.00000000e+00]
 [2.00000000e+00 2.00000000e+00 4.00000000e+00]]
 ---Verify  A^+ * A * A^+ = A^+    ----
[[-5.00000000e-01  1.20000000e+00 -4.00000000e+00  2.40000000e+00]
 [ 5.00000000e-01 -6.00000000e-01  2.00000000e+00 -1.20000000e+00]
 [ 4.49265102e-16 -2.00000000e-01  1.00000000e+00 -4.00000000e-01]]
