In [2]:
import numpy as np
from scipy.linalg import diagsvd
from scipy.linalg import pinv
#from scipy.linalg import inv
from scipy.linalg import svd

m = 4 ; n = 3

A = np.random.randint(0, 5, size=(m, n) )
b = np.random.randint(-1, 3, size=(m, 1))

U, sigma, VT = svd(A)
Sigma = diagsvd(sigma, m, n)
PseudoA = (VT).T @ pinv(Sigma) @ U.T 
print(" ---Verify  A * A^+ * A = A    ----" )
print(  A @ PseudoA @ A )
print(" ---Verify  A^+ * A * A^+ = A^+    ----" )
print(  PseudoA @ A @ PseudoA )

 ---Verify  A * A^+ * A = A    ----
[[ 2.00000000e+00 -1.04337037e-17  1.00000000e+00]
 [ 2.22044605e-16  3.00000000e+00  1.00000000e+00]
 [ 4.00000000e+00 -2.08674074e-17  2.00000000e+00]
 [ 4.00000000e+00  3.07003521e-16  1.05462944e-15]]
 ---Verify  A^+ * A * A^+ = A^+    ----
[[ 1.23487110e-16  5.11672536e-17  1.76330178e-16  2.50000000e-01]
 [-6.66666667e-02  3.33333333e-01 -1.33333333e-01  1.66666667e-01]
 [ 2.00000000e-01 -1.09290310e-16  4.00000000e-01 -5.00000000e-01]]
