In [5]:
import numpy as np 
from scipy.linalg import qr
from scipy.linalg import solve
#

m = 5 ; n = 3

choice = 0 


A = np.random.randint(5, size=(m, n))
b = np.random.randint(10, size=(5))
rank = np.linalg.matrix_rank(A)
print("Matrix rank")
print(A)

Matrix rank
[[0 1 0]
 [2 4 0]
 [3 0 3]
 [4 3 2]
 [1 1 4]]
