In [4]:
import numpy as np
from numpy.linalg import eig

A = np.random.randint(5,size = (5,3))
b = np.random.randint(10, size = (5))

ATA = A.T @ A 

eig_values, eig_vectors = eig(ATA)

print("ATA eig_values")
print(eig_values)
print(" ")
print("ATA eig_vectors")
print(eig_vectors)

ATA eig_values
[80.50839917 13.4135472   3.07805363]
 
ATA eig_vectors
[[ 0.27238144  0.94230378 -0.19460711]
 [ 0.81771051 -0.33329278 -0.46932446]
 [ 0.50710736  0.03129701  0.86131448]]


We know that the eigenvalues of AAT are non-negative and real numbers