In [27]:
from math import sqrt
import numpy as np

#Cholesky A = LLT
 
def cholesky(A):
    n = len(A)

    L = [[0.0] * n for i in range(n)]

    for i in range(n):
        for k in range(i+1):
            tmp_sum = sum(L[i][j] * L[k][j] for j in range(k))
            
            if (i == k): 
                L[i][k] = sqrt(A[i][i] - tmp_sum)
            else:
                L[i][k] = (1.0 / L[k][k] * (A[i][k] - tmp_sum))
    return L
 
A  = np.array([[4, -1, 0], 
            [-1, 4, -1],
            [0, -1, 4]])


L = np.matrix(cholesky(A))


LT = L.T
#a = L @ LT - check
print("U:",LT)
print("L:", L)


U: [[ 2.         -0.5         0.        ]
 [ 0.          1.93649167 -0.51639778]
 [ 0.          0.          1.93218357]]
L: [[ 2.          0.          0.        ]
 [-0.5         1.93649167  0.        ]
 [ 0.         -0.51639778  1.93218357]]
