In [32]:
import numpy as np

a = np.array([[2,-2 , 0, 0, 0],
            [-2, 5, -6, 0, 0],
            [0, -6, 16, 12, 0],
            [0, 0, 12, 39, -6],
            [0, 0, 0, -6, 14]])


def doolittle_decomp(a):
    s = len(a)
    L = [[0 for i in range(s)] for j in range(s)]
    D = [[0 for i in range(s)] for j in range(s)]
    
    for i in range(s):
        for j in range(i, s):
            total = 0
            for k in range(i):
                total += (L[i][k] * D[k][j])
            
            D[i][j] = a[i][j] - total
    
    for j in range(i, s):
        if(i == j):
            L[i][i] = 1
        else:
            total = 0
            for k in range(i):
                total += (L[j][k] * D[k][i])
            
            L[i][j] = int((a[j][i] - total)/D[i][i])
                
    return L, D

L, D = doolittle_decomp(a)
print("L: ",np.matrix(L))
print(" ")
print("D: ",np.matrix(D))

L:  [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 1]]
 
D:  [[ 2 -2  0  0  0]
 [ 0  5 -6  0  0]
 [ 0  0 16 12  0]
 [ 0  0  0 39 -6]
 [ 0  0  0  0 14]]
